# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mineral',
            old_name='optical_porperties',
            new_name='optical_properties',
        ),
    ]
